### ISSUE TITLE
ncurses detection fails on ubuntu-22 / ubuntu-24

### ISSUE THREAD

**Issue by rkabrick** [sstsimulator/sst-core#1090]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
When trying to build sst-core on ubuntu (with ncurses installed via apt-get) the configure script fails to locate ncurses even with `--with-curses` option specified. 
<img width="552" alt="image" src="https://github.com/sstsimulator/sst-core/assets/31963805/6e75a6fd-8b38-4a5c-bff6-a4e96b14b744">

2 - Describe how to reproduce the issue
On a fresh install of ubuntu do: 

```bash
sudo apt install openmpi-bin openmpi-common libtool libtool-bin autoconf python3 python3-dev automake build-essential git libncurses-dev
```

3 - What Operating system(s) and versions 
- Ubuntu 22
- Ubuntu 24

4 - What versions of external libraries (MPI, etc.)
Tried with `libncurses-dev`, `libncurses6`, `libncurses5`, `libncursesw5`, `libncursesw6` 

5 - Provide sha1 of all relevant SST repositories (sst-core, sst-elements, etc)

`tags/v14.0.0_Final`: 0693c06895c9b2be64232a9cd4d17795c0a5ad50

**Comment by berquist** [comment]
The problem is that https://github.com/sstsimulator/sst-core/blob/2f7b13d62a4e047c9dc6f5e0ae238bea41168169/config/sst_check_curses.m4#L50 evaluates the macro before the shell variable when the initially desired behavior was the other way around.  The generated code is
```bash
LIBS="-l$CURSES_LIBS  $LIBS"
```
which then expands to `-l-lncurses -ltinfo ...` which is obviously wrong, but there is something about the library location or linker search paths on non-Ubuntu platforms where it works anyway.

**Comment by berquist** [comment]
@rkabrick Could you try again with the latest version of core from the `devel` branch?

**Comment by jwilso** [comment]
@berquist Is this resolved, or is it still open?

**Comment by jleidel** [comment]
This should be ok now on Ubuntu 22.04 and 24.04.  Good to close

**Comment by berquist** [comment]
Done in https://github.com/sstsimulator/sst-core/pull/1110
