### ISSUE TITLE
Intermittent segfault for --load-checkpoint when using sst threads

### ISSUE THREAD

**Issue by kpgriesser** [sstsimulator/sst-core#1157]
1 - Detailed description of problem or enhancement

Performing stress testing for sst threading with checkpoint/restart.  I'm seeing intermittent segfaults when restarting from a saved checkpoint. I'm seeing this with my components and sst-core compiled with -O0  as well.
I ran a parameter sweep of number of components and number of simulation threads and am seeing the failure only about 1% of the time.  I can be reproduced by repeating a test where a parallel checkpoint is reloaded repeatedly.

2 - Describe how to reproduce the issue

In my case I have 9 components communicating via links clocked at 1ns.
I run sst with -n 7 for  10000 clocks using --checkpoint-period=1000ns ( so 10 checkpoints are generated ).
Then reload a checkpoint using -n 7.
Repeat this about 100 times and the simulation seg faults.

To run my specific test case use the same branch referenced in #1156

```
git clone git@github.com:tactcomplabs/sst-bench.git
cd sst-bench
git checkout bug-mpi-checkpointing
mkdir build && cd build
cmake -DSSTBENCH_ENABLE_TESTING=ON ../
make -j -s && make install
cd ../test/grid
./bug-restart.sh
```

The script will error exit if one of the simulations fail.

3 - What Operating system(s) and versions
Ubuntu 22.04.5 LTS

4 - What versions of external libraries (MPI, etc.)
mpirun (Open MPI) 4.1.2
sst is compiled with MPI support but it is not used in this test case

Initial look at the same test on  macOS Sonoma 14.6.1, I'm seeing intermittent hangs.
sst-core is compiled without mpi support.

5 - Provide sha1 of all relevant SST repositories (sst-core, sst-elements, etc)

```
# commit 7848d804fbdb0f936736f36b67f8f636547fd7f9 (HEAD -> master, origin/master, origin/HEAD)
# Merge: 0d412e16 1cc35cc8
# Author: SST AutoTester <sstbuilder@sandia.gov>
# Date:   Thu Oct 3 08:07:23 2024 -0600
```

When sst-core is compiled with -O0 the simulation fails as well.

**Comment by feldergast** [comment]
The 11 checkpoints is probably because you don't detect that the simulation ends until the next sync point.  So, if the simulation ended after the sync at 10us, it wouldn't detect it until  the next sync at 11us (at least I'm assuming the sync interval is 1us).  Couple this with the fact that the checkpoint fires before the exit check and you get your extra checkpoint.  It would likely happen for any end time that happens between syncs.  We'll have to see if we can switch the order of the checks, or if we're stuck with this behavior.

**Comment by feldergast** [comment]
I'll look at the reinitialization path for the Exit object on restart and see if we have a race somewhere.

**Comment by feldergast** [comment]
Looking at this code again:
        
        if ( /*num_ranks_+.rank == 1*/ min_part_ == MAX_SIMTIME_T ) {
            if ( exit_->getRefCount() == 0 ) { endSimulation(exit_->getEndTime()); }
        }

I realized that if statement is checking for the case where there are no link crossing partition boundaries, so in this case, the code should never be executed.  So, it looks like there are a couple things that aren't getting initialized correctly (min_part and exit_) in whatever race condition happens.

**Comment by feldergast** [comment]
> The 11 checkpoints is probably because you don't detect that the simulation ends until the next sync point. So, if the simulation ended after the sync at 10us, it wouldn't detect it until the next sync at 11us (at least I'm assuming the sync interval is 1us). Couple this with the fact that the checkpoint fires before the exit check and you get your extra checkpoint. It would likely happen for any end time that happens between syncs. We'll have to see if we can switch the order of the checks, or if we're stuck with this behavior.

I confirmed that the extra checkpoint is expected behavior for the case where your checkpoint triggered during the same sync that detected exit. I'll look into seeing if we can switch those checks without causing other issues.

**Comment by feldergast** [comment]
Looks like the barrier that was supposed to be after reinitialization of the Exit object (which is static, so only thread 0 checkpoints it) was accidentally put in the checkpoint code instead of the restart.  I suspect that's likely the root of this issue as there could be a race condition where some threads didn't get the right data when creating the new SyncManager.  I have added the fix to the current PR I am working on, but if you want to test it, you can move barrier (initBarrier.wait()) after the serialization of m_exit() from the checkpoint function to the restart function.
