### ISSUE TITLE
Need more useful error messages for failed loading of libraries, showErrors should always be true?

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#138]
##### New Issue for sst-core

`1` Detailed description of problem or enhancement
No useful error printing for failed loading of libraries.  I don't really know why showErrors is ever false. If there are undefined refs or problems with the search path, I just get a really generic "not loaded" error.  I have to go into the code and set showErrors to true before I get the useful error message about why my python import failed.

`2` Describe how to reproduce

`3` What Operating system(s) and versions 

`4` What version of external libraries (Boost, MPI)

`5` Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

`6` Fill out Labels, Milestones, and Assignee fields as best possible

Line 545 in factory.cc

genPythonModuleFunction
Factory::getPythonModule(std::string name)
{
    std::string elemlib, elem;
    std::tie(elemlib, elem) = parseLoadName(name);

```
const ElementLibraryInfo *eli = findLibrary(elemlib, false);
if ( eli )
    return eli->pythonModuleGenerator;
return NULL;
```

}

**Comment by nmhamster** [comment]
@jjwilke there are reasons why this is not always set relating to complex handling of paths by other tools in the SST suite. Can you be more specific about the context of the issue you are reporting?

**Comment by nmhamster** [comment]
@jjwilke we also do not always print the errors because this allows Python scripts to attempt loads and perform actions if they are not found.

**Comment by jjwilke** [comment]
import sst.macro has failed because SST_LIB_PATH was not set. Or because of undefined references. Or because we didn't provide a gen_python_module function.  Chasing down the load failure required a very frustrating printf session (particularly the first time around).  It seems that the error printing could be vastly improved.  I don't think the default behavior should be to print a cryptic "Opening element library %s failed" ... or even worse to just generate a Python ImportError.

**Comment by nmhamster** [comment]
@jjwilke you most likely have not registered the directory in the SST configuration (using `sst-register`). Without this the directory is not searched for resolving imports. Resolving when and when-not to print errors is complicated in the current tool-chain (because of so many different use cases). It might be worth a design discussion so we have the use cases explored for SST v6.1/7.0.

**Comment by jjwilke** [comment]
I'll label enhancement. We can punt on this for now.

**Comment by nmhamster** [comment]
@jjwilke thanks, we may need to work on even more generic loading handlers but that probably won't make v6.0.

**Comment by bjmoor** [comment]
The way the Python piece is acting is the "correct" way - in that it represents what Python does when it attempts to import a library which cannot be found:  Throws an ImportError.   It is actually the Python interpreter throwing that error.   When writing a simulator (aka, the python piece), and you wish to present a user-friendly error message, you should wrap your import statement with a try/catch, and present to the user the error message that you would like.

If SST emitted an error message on a failed import, it would limit the Simulator writer's ability to manage the error condition.

Also, there is nothing that guarantees that there isn't an additional Python library installed on the system with an 'sst' name.  We should not prevent such libraries from being loaded by throwing an error when something in that namespace fails to resolve to the SST loader.

**Comment by bjmoor** [comment]
I can enable better error messages in the ImportError for missing libraries, however, any modules (like `merlin`) that provide a Python-library extension will need to add a line to the top of their module:

```python
from __future__ import absolute_import
```

According to the python documentation, this should not be necessary with Python 2.7, but according to real-world testing, it still is.    What this will do is prevent Python from asking for 'sst.sys' when 'import sys' is found within a Element library's python module.

One of the current challenges is that our Importer cannot currently say "we handle all '`sst.*`' imports, because of the relative importing that occurs.  If we force sub-modules to use absolute importing, we won't be presented with the situation of python attempting to resolve system-provided modules by assuming they are found under the SST module.

**Comment by jjwilke** [comment]
Bringing this back. My current recommendation would be to pass along a `std::ostream` that collects error messages. When a library fails to load and produces a *fatal* error in the process, then all the errors get printed. `showErrors` would no longer be a parameter. We collect error strings and always show errors on fatal.
