### ISSUE TITLE
Fix sst-info with new ELI

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#198]
The new ELI breaks sst-info.  This needs to be fixed before 7.0.

**Comment by nmhamster** [comment]
Can you confirm that `sst-info` command will work for old ELI right? Its just it does not report the new ELI contents?

**Comment by allevin** [comment]
I did a clean build of both sst-core and sst-elements (devel branches) and confirmed that sst-info works with the old ELI, but does not report the new ELI structure.  It does detect elements with the new ELI, but reports 0 for all entries.  This works because the top level "old eli" object still exists.
