### ISSUE TITLE
Warnings while extracting 7.2.0 package

### ISSUE THREAD

**Issue by tks2004** [sstsimulator/sst-core#341]
New Issue for sst-core
----------------------

While extracting the sst-core, elements and macro packages for the 7.2.0 version, there are warnings. 

tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'

These are not seen with 7.1.0 packages
$tar -zxvf sstcore-7.2.0.tar.gz  or
with
$gunzip sstcore-7.2.0.tar.gz
$tar -xvf sstcore-7.2.0.tar

**Comment by allevin** [comment]
Confirmed, this affects all 7.2 builds (sst-core, sst-elements and sst-macro).  However the problem is NOT CRITICAL and a minor annoyance, and can be safely ignored.

On this release set, the tar.gz files were created using "make dist" when running on a Mac, and tested on the same platform.   The release checklist does not call out for a specific platform to run the "make dist" on.

The errors are caused by the bsd based tar utility on Mac which adds extra data that the GNU tar utility on Linux does not understand.  

See http://lifeonubuntu.com/tar-errors-ignoring-unknown-extended-header-keyword/ 

To correct this for future releases, the release checklist will be modified to perform the "make dist" on a linux machine, and test the final tar.gz files on both Linux and Mac's.
