### ISSUE TITLE
Implement SharedRegion::merge(uint8_t *target, const uint8_t *newData, size_t size)

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#37]
This version of SharedRegion merge is not implemented which means that the Bulk Merger fails.  You are put to Bulk Moves as soon as you call getRawPtr(), which means you can't get raw access to the region and have it propagate to other ranks.

**Comment by bjmoor** [comment]
I'm guessing you should use the InitializedSharedRegionMerger() merger.  That Merger has the call implemented.   The default 'SharedRegionMerger::merge()' does not implement that method on purpose, as there is no guarantee of initialization, and thus no way for it it know how to merge.

**Comment by feldergast** [comment]
The code path for getGlobalSharedRegion() does include a memset, so the region is guaranteed to be initialized. I propose we make SharedRegionInitializedMerger the default and don't force the user to figure out which merger to use.  That way, we can support both the changeset and bulk usage as the default and only require a different merger be specified if they want something more optimized.

**Comment by bjmoor** [comment]
That `SharedRegionMerger` does not implement `merge(uint8_t *target, const uint8_t *newData, size_t size)` was a decision we made when first deciding on the API.  The idea was to discourage accidents and mistakes.

If the user of the API is going to use the raw pointer access mode, there's no way to generically perform a merge between ranks, as we don't know what data has been set by each rank, or be able to offer debug assistance if multiple ranks write to the same addresses.  That is why we encourage the use of the `modifyRegion()` call.  We can track what each rank has updated, and merges make sense.   

Obviously, that `modifyRegion()` call will not work for all scenarios, and so we offer the raw pointer access as well.  The expectation then is because you are already doing "advanced" work (requiring direct pointer access to the shared region), the extra step of providing an intelligent `SharedRegionMerger` should not be too bad.  We even provide an example that only requires you specify what value of a byte should be used to consider that byte "uninitialized", and thus not needed to be copied over into the target byte in the merge.  That's `SharedRegionInitializedMerger`.

The benefit of this strategy is that we require the user of the API to think about exactly what they're wanting merged.  Yes, it's an extra few keystrokes to specify `new SharedRegionInitializedMerger(initByte)` as the argument to `SharedRegionManager::getGlobalSharedRegion()`, but it makes the user aware of what they're choosing to do.

**Comment by feldergast** [comment]
We can relatively easily generically merge anything as long as we initialize the regions to known values (which we already do).  You can still detect the vast majority of conflicts in the merge and warn the user (the one case you can't detect is where one rank sets the byte to the initialization value and another rank sets it to something else; this would be seen as only one rank setting the value and would not trigger an error).

I would still push to make auto merging of anything the default.  If we don't do this, the nuances of how the API work may be confusing to users.  However, if we don't plan to make that change, we still need to make the API (or it's implementation at least) more friendly.  It took me multiple hours to track down a failure in a parallel run to the SharedRegion code.  The SharedRegionMerger silently decided not to do the merger.  We at least need to add a useful error message here, as to why the data isn't being propagated across ranks.  Also, the error persisted even after I switched to using ModifyArray() to build the array.  It turns out the read code was using the raw pointer to avoid a function call during simulation.  The pointer was being initialized in the constructor using getRawPtr(), which was enough to force the SharedRegionManager to use the Bulk copy mechanism, even though no writes were done using it.  Once I moved the initialization of the pointer to after the publish() call, things started working.

Additionally, while playing around with things, I noticed that the SharedRegionMerger using ChangeSets doesn't seem to actually detect conflicts during the merge.  I will open a new bug on that.

**Comment by feldergast** [comment]
I withdraw my request to make bulk merger the default.  While I think the merging wouldn't be much of a problem, I think we need to push people to the modifyArray() function so that we can guarantee thread safety.  However, it would be good to have a rational error message when getRawPtr() is used with an incompatible merger.  Can we just add the error message in SharedRegion::merge(uint8_t *target, const uint8_t *newData, size_t size) so that it faults when called instead of silently failing to merge?
