### ISSUE TITLE
Move most of params.h into params.cc for compile times

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#377]
params.h is 10-20% of compile time due to implementation in the header file.
Shift most of the instantiation into .cc file.

**Comment by feldergast** [comment]
I'm actually working on this because there are some other issues with API where a non-intuitive version of the find function is used.  For example find<bool>("name","false") will use the find<T>(std::string,T) instead of find<T>(std::string, std::string), so actually returns true.  I need to rework the API a little to fix this and will move instantiation into the .cc file while I'm at it.

**Comment by nmhamster** [comment]
Is this in `params.h` or is it also caused by the (templated) calls into `from_string.h`?

**Comment by nmhamster** [comment]
BTW - the compile times are not really a significant concern for SST users yet. The discussion at this point has been how do we keep them from getting out of hand while adding more and more templating into the mix. Given the work on actually using SST (for analysis), I'd argue this is fairly low priority once the bugs that @feldergast have been addressed.

**Comment by jjwilke** [comment]
from_string.h (according to templight) is not the biggest offender (although it contributes). It’s the use of, e.g. operator[] on any STL maps defined in class Params {}

**Comment by jjwilke** [comment]
This got fixed in 7259ddcf7e953f26d46b5b80a9cc611a94a9ee5f, PR #378
