### ISSUE TITLE
sst-info segfault

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#443]
sst-info segfaults at exit on Mac only (Linux runs fine).

**Comment by jjwilke** [comment]
Well, that’s what I get for using `unique_ptr` and and trying to make core sanitizer friendly.

Mac does some awesome private memory/segmentation things during `dlopen`. If I call operator new during `dlopen`, these allocations stay local to the .so file. When I `dlclose`, any memory allocated during `dlopen` ceases to be valid. You would think something you allocated with `operator new` would stay permanent – but no. `unique_ptr` deletes the object, the pointer is no longer valid following `dlclose`, and you get the segfault.

Honestly, we’ve been getting lucky prior to 9.0 since we just leaked memory and didn’t try to clean up. For now, I can get devel working by just leaking memory. It will take some non-trivial finessing to clean up memory during `dlclose`, not just `cxa_finalize`.

**Comment by jjwilke** [comment]
Updated: the destructor of a class defined in `libX.so` is getting called, which then gets `dlclose`d. The destructor code is no longer valid, leading to the segfault. This may not have been happening prior to 9.0.

**Comment by gvoskuilen** [comment]
Segfault is fixed.
