### ISSUE TITLE
canceling an event on a self-link

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#544]
Is there any way to cancel an event sent on a self-link?
----------------------
My component has sent itself a message to wake up at time t1 to do something.  Before t1, something happens so that the component need to wake up earlier, so it sends a self message to arrive at t2 (< t1).  It no longer needs to wake up at t1.  Can I cancel the message that was due to arrive at t1?  I would like to try this because there are many wake-up events that end up not being needed.

I tried to recv() on the self-link to get rid of the unneeded message, but got an error.  Cannot call recv on a link with an event handler installed (non-polling link.

Thanks.

**Comment by feldergast** [comment]
There is no way to cancel an event once it's sent.  Even if you have a pointer to the event you sent, there's no easy way to know where it's at in the event queue.  Trying to find and cancel the event would be more computational intense than just letting the event be delivered and ignoring it (and with the current data structure used for the queue, almost impossible since you can only pop off the head of the queue).

The recv() function doesn't work in this case for two reasons.  First, it only works if you set the link to be polling (i.e. the event never goes into the main event queue, it goes into a link specific queue that you have to call recv() on to get an event).  Second, events are delivered using recv() until at or after their delivery time, so trying to pull it out early won't work.

I have built something similar in the past, where a component needed exactly one wake-up event.  I added a canceled field to my wake-up event and kept a pointer to the current valid wake-up event.  If I needed to wake up earlier, I set the canceled flag on the current event and put a sent a new one with the new wakeup.  The event handler then checked the canceled flag and returned immediately when it was set.  For my case, this was faster than going through the work to recognize that nothing needed to be done.  CAUTION:  Using this method, will only work reliably for events sent on self links, and you need to be careful not to change any state in the event other than the canceled flag.  Changing any of the internal state, could cause the event to mess up the event queue.

**Comment by gunney1** [comment]
Thanks for the suggestion, feldergast.  I think your idea should work for my issue.
