### ISSUE TITLE
Invalid MIT-MAGIC-COOKIE-1 key

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-core#619]
With a fresh installation of sst-core, when I run `sst` I get the following output:

```
nic@linux:~/$ sst --version
Invalid MIT-MAGIC-COOKIE-1 keySST-Core Version (-dev, git branch : master, SHA: b847b7db63c0e2294bc6ecc7eac29ec981d432af)
```

No matter what I run, if it is run with `sst`, the `Invalid MIT-MAGIC-COOKIE-1 key` is output. 

Any thoughts?

Here are the relevant packages I used:
Ubuntu 20.04.2 LTS
OpenMPI - 4.0.3
sst-core - git tag v10.1.0_Final
hdf5 - 1.10.5
zoltan - 3.83

**Comment by feldergast** [comment]
Isn't that an x-server error of some sort?  Not sure why you'd be getting it with SST since there is no graphics code in it.  A bit of searching shows that this seems to be an issue with Ubuntu 20.04 and how it interacts with MPI_init().  There are quite a few suggestions on-line for how to address this, but since I can't reproduce the issue, I can't test any of them.

**Comment by nicmcd** [comment]
Hmmm... yes, I can't figure out how to get rid of it, but that's not your fault :) Thanks for the pointers.
