### ISSUE TITLE
SimpleNetwork should be moved to sst-elements

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-core#624]
https://github.com/sstsimulator/sst-core/blob/9ee1db28c6c45129f685179e086739b9d3df83ea/src/sst/core/interfaces/simpleNetwork.h#L39

SimpleNetwork is a contract between particular sst-elements. It makes more sense to define it there as it isn't part of the "core". The same logic should be applied to simpleMem and stdMem.

**Comment by feldergast** [comment]
They started in elements and that caused all sorts of issues (though it was long enough ago that I don't remember what they were exactly), so they were moved into the core.  These interfaces are used by external element libraries as well as libraries in sst/elements, so moving them to sst/elements would create an extra dependency for external elements.  We've found that having these basic interfaces in the core was the right approach.

**Comment by nicmcd** [comment]
What is the limit to this methodology? If I create two external element repos that need to collaborate via an API, should I publish that API here in sst-core? Doesn't that seem illogical?

**Comment by feldergast** [comment]
We actually have interfaces defined in elements as well (Hermes is an example, as is pretty much every SubComponent API).  The ones we moved into core are ones that were heavily used across different element libraries and we wanted to promote their use instead of making new interfaces.  If other interfaces rise to that level, then yes, we will move them into the core.  Otherwise, they live in sst/elements or external element libraries.
