### ISSUE TITLE
clang-format-12 reveals 13122 code formatting escapes

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#652]
**Summary**
The `.clang-format` configuration currently in the devel branch executed using clang-format-12 reveals 13,122 code formatting test escapes.  While many of these are very trivial, if we seek to use clang-format in PR testing, then the devel source tree should run clean.  I've attached the clang-format dump.  

**Configuration:**
- Ubuntu 20.04LTS
- clang version 10.0.0-4ubuntu1 (installed from llvm apt-repo)
- clang-format version 10.0.0-4ubuntu1
- `clang12-format --dry-run./src/sst/core/*.cc`

[clang-format-12.txt](https://github.com/sstsimulator/sst-core/files/6592137/clang-format-12.txt)

**Comment by feldergast** [comment]
Looks like there's some formatting that we've been largely ignoring and may want to change the standard to match (for example, space after/before paren in if statements).  I'll take a more detailed look though the list.  For some of the ones I've seen, I can't tell what rule it's violating.  Is there any way to include that in the output?  For example, I don't know what rule this is violating:

namespace SST {
                              ^

**Comment by feldergast** [comment]
I'll post any issues I see looking through the output in the comments, one issue per comment.

It looks like it's not correctly checking the formatting for the out-of-line definitions of functions.  The format should be:

return_type
Class::functionName(...)
{
}

**Comment by jleidel** [comment]
> Looks like there's some formatting that we've been largely ignoring and may want to change the standard to match (for example, space after/before paren in if statements). I'll take a more detailed look though the list. For some of the ones I've seen, I can't tell what rule it's violating. Is there any way to include that in the output? For example, I don't know what rule this is violating:
> 
> namespace SST {
> ^

Clang-Format is not very good at telling you "why" it failed.  There is an external script that helps in this case: 
https://github.com/Sarcasm/run-clang-format

The tool will give you a diff of the required changes.  

`./run-clang-format.py --clang-format-executable clang-format-12 ./src/sst/core/sstpart.cc`

```
--- ./src/sst/core/sstpart.cc	(original)
+++ ./src/sst/core/sstpart.cc	(reformatted)
@@ -20,19 +20,16 @@
 SST_ELI_DEFINE_CTOR_EXTERN(SSTPartitioner)

 void
-SSTPartitioner::performPartition(PartitionGraph* UNUSED(graph))
-{
-  Output &output = Output::getDefaultObject();
-  output.fatal(CALL_INFO, 1, "ERROR: chosen partitioner does not support PartitionGraph");
+SSTPartitioner::performPartition(PartitionGraph* UNUSED(graph)) {
+    Output& output = Output::getDefaultObject();
+    output.fatal(CALL_INFO, 1, "ERROR: chosen partitioner does not support PartitionGraph");
 }

 void
-SSTPartitioner::performPartition(ConfigGraph* UNUSED(graph))
-{
-  Output &output = Output::getDefaultObject();
-  output.fatal(CALL_INFO, 1, "ERROR: chosen partitioner does not support ConfigGraph");
+SSTPartitioner::performPartition(ConfigGraph* UNUSED(graph)) {
+    Output& output = Output::getDefaultObject();
+    output.fatal(CALL_INFO, 1, "ERROR: chosen partitioner does not support ConfigGraph");
 }

-}
-}
-
+} // namespace Partition
+} // namespace SST
```

**Comment by jleidel** [comment]
> I'll post any issues I see looking through the output in the comments, one issue per comment.
> 
> It looks like it's not correctly checking the formatting for the out-of-line definitions of functions. The format should be:
> 
> return_type
> Class::functionName(...)
> {
> }

Is this the latest coding standards?  https://sst-simulator.org/SSTPages/SSTDeveloperCodingStandards/

**Comment by feldergast** [comment]
That is the only one we've published (over 10 years ago), and is a good starting point.  In practice, things have diverged from there, and the team may make more changes as we go through this process.  Including adding things that were not specified before.  We'll try to align the coding standards with what's already in the codebase, where possible. The items I put here are things that have become the "norm" since that page was put up.

**Comment by feldergast** [comment]
I made a run through the .clang_format file and cleaned it up a bit to reflect changes made since the coding standards were posted.  It reduced the number of reported issues a somewhat.  The one thing I can't seem to figure out (and maybe it's not possible) is brace placement on function definitions.  In a class, the opening brace should be on the same line and out of class definitions should have it on the following line.  For example:

class Number {
    int getNum() {
        return 5;
    }
};

and

int
Number::getNum()
{
    return 5;
}

The parameter that controls this seems to be the same for both cases.  Does anyone know if it's possible to have the brace placement be different for these two cases in clang-format?

**Comment by donofrio** [comment]
Making some modifications to .clang_format (attached) the escape count is reduced to 11090.  Inspecting the diffs produced by `run-clang-format.py`, the majority of the remaining issues appear to be inconsistent spacing within parenthesis and where a function return type is defined. To address the question above, the existing value of `AlwaysBreakAfterReturnType: TopLevelDefinitions` appears to be the closest option.  For exceptions we could wrap things in `// clang-format off ... // clang-format on`. Finally, FWIW, looking across the sst-core codebase the formatting issues seem fairly evenly distributed.

[clang_format.txt](https://github.com/sstsimulator/sst-core/files/6656382/clang_format.txt)

**Comment by feldergast** [comment]
Thanks @donofrio.  I don't think we want to wrap a bunch of exceptions.  There would be too many.  Looks like we'll just have to live with the opening braces for function definitions being on the same line in all cases.  I went through the options for clang12 a while back and will compare this version of clang_format against some of the changes I was looking at making.

I think the last piece of the puzzle will be getting the IncludeCategories stuff working.  For includes, we would prefer the following order:

- sst_config.h always goes first in .cc files and never gets included in .h files
- corresponding header goes second (i.e. link.h in link.cc), though this one we may be able to relax since we'll eventually be testing for "include what you use".
- other sst core header files
- external header files (not sure we have many, if any, of these in core)
- system header files

The external and system header files should be included using <> version of \#include and all others should use quote version.  Within each block, the headers should be included in alphabetical order.

**Comment by donofrio** [comment]
Looking at the include ordering, I've attached a `clang_format` that hopefully does most of what you're looking for:

- sst_config.h placed as highest priority _but_ does not flag if sst_config.h is included in a header file (priority -1)
- corresponding header is placed directly below sst_config (Priority 0)
- all headers that look like "`sst/core/`" are placed (Priority 1)
- all other headers that are wrapped in quotes but do **not** contain `sst` are placed next (Priority 2)
- all headers wrapped in angle brackets are last (Priority 3)
- all headers sorted alphabetically in their respective groupings

Final quirk: I have clang_format set to merge and reorder across blocks, but if blocks are separated by comments or anything other than whitespace it does not appear to merge across those blocks, only within them.  If this is insufficient, we could possibly get more aggressive with a clang-tidy script
[clang_format.txt](https://github.com/sstsimulator/sst-core/files/6710692/clang_format.txt)

**Comment by calewis** [comment]
@jleidel can we close this now that core has been formatted and we have a script to check formatting running in tests?

**Comment by jleidel** [comment]
@calewis, absolutely.  closing this now.
