### ISSUE TITLE
Component/SubComponent to MPI rank mappings

### ISSUE THREAD

**Issue by jj16791** [sstsimulator/sst-core#901]
I'm trying to create a selection of new SST components, comprising an OS-style component linking to many core-style components. I'm exploring different options to set up these links (either through SST::Links or having the core-style components be a subcomponent/component extension of the OS-style component). Is it possible to map the parent component and its subcomponents/component extensions to different MPI ranks when running multi-core simulations?

If this is not the case, is it possible to create components within a component defined in the passed `.py` configuration file and have them assigned different MPI ranks? For example, spawn `n` core-style components from within an OS-style component defined in the passed `.py` configuration file through some sort of parameter such as `num_cores` (and have them reside on different MPI ranks.

**Comment by feldergast** [comment]
Neither of these scenarios is possible.  SubComponents and ComponnentExtensions are specifically designed to be part of their parent Component, and Components cannot spawn other Components.  This is due to the fact that the partitioning happens before any of the simulation objects are constructed.

However, there is a mechanism to simplify user generation of input files.  It is possible to write a Python module that is part of the element library that can be used in the Python input file.  This python file could have an abstraction that includes the OS component and the cores, allowing the user to specify the number of cores and having the Python module generate the appropriate components.  The Merlin element library uses the mechanism to simplify the instantiation of network topologies.  If this sounds like an approach you’d like to explore, I can provide more information.

**Comment by jj16791** [comment]
Thank you for the reply @feldergast. I'll explore Python module generation route!

**Comment by gvoskuilen** [comment]
@jj16791 Is it ok to close this now?

**Comment by rdfriese** [comment]
@feldergast I hate to revive a closed issue, but if your offer for more information on this approach still stands I would appreciate it!
