### ISSUE TITLE
Python 3.11 cpython libpath error

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#927]
In python 3.11, cpython no longer includes the current directory in the libpath which makes many SST tests and python module imports fail. This causes, among others, Merlin, Ember, and MemHierarchy tests to fail.

**Comment by feldergast** [comment]
This is due to a new security feature in Python 3.11. There is a new -p option that causes Python to not add the current working directory and the directory of the script to sys.path.  However, not adding those directories seems to be the default behavior in embedded interpreters (or at least that is what we are seeing in SST).  Still trying to track down the right way to make sure the paths are added.

**Comment by feldergast** [comment]
Fixed in #930
